version: "3.8"

services:
  # hub:
  #   env_file:
  #     - hub.env
  #   image: icedream/waterfall:latest
  #   restart: unless-stopped
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - extBridge
  #     - minecraft
  #   ports:
  #     - 25565:25565
  #   volumes:
  #     - ./logs/waterfall:/opt/waterfall/server/logs:rw
  #     - ./plugins/waterfall:/opt/waterfall/server/plugins:ro
  survival:
    image: "marctv/minecraft-papermc-server:latest"
    restart: always
    env_file:
      - survival.env
    volumes:
      - ./worlds/survival:/data:rw
    networks:
      - extBridge
      - minecraft
    ports:
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true

networks:
  extBridge: { driver: bridge }
  minecraft: { internal: true }
