version: "3.8"

services:
  hub:
    env_file:
      - hub.env
    image: icedream/waterfall:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - bridge
      - minecraft
    ports:
      - 25565:25565
    volumes:
      - ./logs/waterfall:/opt/waterfall/server/logs
      - ./plugins/waterfall:/opt/waterfall/server/plugins

networks:
  minecraft: { internal: true }
  extBridge: { driver: bridge }
